language: node_js

node_js:
  - "lts/*"

cache:
  yarn: true

script:
  - cd stories/
  - yarn install
  - cd ../
  - yarn lint
  - yarn flow
  - yarn test -- --coverage
  - yarn build

before_deploy:
  - yarn build-storybook

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: storybook-static
  on:
    branch: master

after_script:
  - yarn codecov